### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'errno'/dropbox-fs 0.1_11

### ISSUE THREAD

**Issue by zopyx** [btimby/fs-dropbox#2]
I am calling
fs = DropboxFS(APP_KEY, APP_SECRET, 'dropbox', request_token, access_token)
print fs.makedir('a')

and get the following:

sucmac:pp.buildout ajung$ bin/zopepy dp.py
<dropbox.session.DropboxSession object at 0x10f82fa50>
https://www.dropbox.com/1/oauth/authorize?oauth_token=xRFR7iazM5ph5UsD
Traceback (most recent call last):
  File "bin/zopepy", line 46, in <module>
    exec(compile(**file__f.read(), __file**, "exec"))
  File "dp.py", line 36, in <module>
    print fs.makedir('a')
  File "/Users/ajung/.buildout/eggs/dropboxfs-0.1_11-py2.7.egg/dropboxfs.py", line 446, in makedir
    self.client.file_create_folder(path)
  File "/Users/ajung/.buildout/eggs/dropboxfs-0.1_11-py2.7.egg/dropboxfs.py", line 242, in file_create_folder
    errno=e.status)
  File "/Users/ajung/.buildout/eggs/fs-0.4.0-py2.7.egg/fs/errors.py", line 92, in **init**
    super(OperationFailedError,self).**init**(**kwds)
TypeError: **init**() got an unexpected keyword argument 'errno'

**Comment by freak3dot** [comment]
Could this be related to unlinking your Dropbox account from the Dropbox security settings?

**Comment by freak3dot** [comment]
See this related commit: https://github.com/smartfile/fs-dropbox/commit/52bdf3446a16c1508163ecaca9c75023464503ac
